### ISSUE TITLE
Generic issue notified by autoeq2camilladsp

### ISSUE THREAD

**Issue by marcoevang** [Ebert-Hanke/autoeq2camilladsp#55]
I built autoeq2camilladsp with rustup 1.26.0 on a NUC6CAYH running ubuntu 23.04 with no problems.
Then I launched the executable file and selected the headphone. I received the following diagnostics:
"...Something went wrong unfortunately :(
The eq data could not be parsed. "

The same happens when selecting other headphones and other options (e.g. device section, crossfeed filter type, etc.).

**Comment by skeletony007** [comment]
I am using macOS Ventura 13.5 (Apple Silicon) I receive the same error

```
  ...Something went wrong unfortunately :(
The eq data could not be parsed.
```

I encountered this problem both when I freshly installed the latest release, and also when I used an old version I had on my system (that I know has worked in the past).

Perhaps the format of Jaakko Pasanen's [AutoEq](https://github.com/jaakkopasanen/AutoEq) has changed since I last used `autoeq2camilladsp`.

**Comment by Ebert-Hanke** [comment]
Thank you for the heads up! I checked and it is actually a change in the AutoEq datastructure. I will adjust the tool soon. Thank you for your patience :)

**Comment by Ebert-Hanke** [comment]
I merged a fix and created a new beta release for testing. If you happen to have the time, please check if the tool now works again as desired. Thank you!

**Comment by marcoevang** [comment]
I tested the updated version of your tool, and it works quite well.
Thank you so much for your great work.

**Comment by Ebert-Hanke** [comment]
You are very welcome. New 0.5.3 release is published. Thanks for testing!
